# Creazione del corpus

In [1]:
import pandas as pd

In [2]:
df_corpus = pd.read_csv("trainset/desegma-it.subTaskA.shared.train.0923-1220.csv")

In [3]:
df_corpus

                                                    text  label
0      Ed ora che le due ragazze sono salve, si può f...      0
1      Tale affermazione ha suscitato numerose reazio...      1
2      L'Akp si conferma primo partito, ma dovrà form...      0
3      La decisione del governo italiano "è in linea ...      0
4      È nel cuore del quartiere di Trastevere, in un...      1
...                                                  ...    ...
33133  La manovra del PNRR, l’occasione di rilancio, ...      1
33134  Preoccupanti condizioni sulle isole greche e a...      0
33135  Al momento sono 18, invece, i feriti. Ancora n...      0
33136  Anche quest'anno, infatti, ad agosto, nonostan...      0
33137  Perché Ahmadreza Djalali, medico e ricercatore...      0

[33138 rows x 2 columns]

In [4]:
df_corpus["label"].value_counts()

label
0    16569
1    16569
Name: count, dtype: int64

In [5]:
df_corpus[df_corpus["label"] == 0]

                                                    text  label
0      Ed ora che le due ragazze sono salve, si può f...      0
2      L'Akp si conferma primo partito, ma dovrà form...      0
3      La decisione del governo italiano "è in linea ...      0
6      Abbraccia un trentennio - dal 1989 ad oggi - e...      0
7      Con un tennis da sogno la nostra bella campion...      0
...                                                  ...    ...
33131  Il ritocchino al rialzo inciderà sulle multe p...      0
33134  Preoccupanti condizioni sulle isole greche e a...      0
33135  Al momento sono 18, invece, i feriti. Ancora n...      0
33136  Anche quest'anno, infatti, ad agosto, nonostan...      0
33137  Perché Ahmadreza Djalali, medico e ricercatore...      0

[16569 rows x 2 columns]

### Creazione Training Set dal train Set (1000 e 1000)

In [6]:
train_class0 = df_corpus[df_corpus["label"] == 0].sample(n=1000, random_state = 42)

In [7]:
train_class1 =  df_corpus[df_corpus["label"] == 1].sample(n=1000, random_state = 42)

In [8]:
df_train = pd.concat([train_class0, train_class1])
df_train

                                                    text  label
9610   Il dato emerge dall’ultima pubblicazione dell’...      0
29392  Ora si fanno i conti. Ecco allora tutti i Paes...      0
24989  Lo stesso purtroppo non si può dire per la " f...      0
14323  Ma oggi il materiale diffuso sul web, che most...      0
5346   Gli specialisti del Gis, peraltro in continuo ...      0
...                                                  ...    ...
26090  Si dice che l'uomo, di età compresa tra i 38 e...      1
9218   La strage di Detroit, con cinque innocenti mas...      1
25409  L’omicidio è avvenuto in un’abitazione di piaz...      1
27653  I dispositivi Android, spesso acquistati da fa...      1
1377   Stanford, attraverso un'interessante collabora...      1

[2000 rows x 2 columns]

In [9]:
df_train["label"].value_counts()

label
0    1000
1    1000
Name: count, dtype: int64

### Creazione del validation set dal training set: 1000 documenti (500 e 500)

In [10]:
val_class0 = df_corpus[df_corpus["label"] == 0].drop(train_class0.index).sample(n=500, random_state=42)

In [11]:
val_class1 = df_corpus[df_corpus["label"] == 1].drop(train_class1.index).sample(n=500, random_state=42)

In [12]:
df_val = pd.concat([val_class0, val_class1])
df_val

                                                    text  label
27441  Benvenuti nell’era della globalizzazione e del...      0
15383  "Al momento oer questioni di sicurezza non è p...      0
21517  Quanto i nostri sensi, primordiali e non, si s...      0
22180  Lo stabilisce la Cassazione disponendo un nuov...      0
19907  L’Nx, che dovrebbe uscire in autunno ed esser ...      0
...                                                  ...    ...
14652  Tuttavia, il voto ha suscitato indignazione e ...      1
12239  Molti spot realizzati in Italia e all’estero, ...      1
23181  Diciamo, con un'ironia rassegnata e un pizzico...      1
21047  Secondo Legnini, lUtilsimoUBLICO goal dell'Ita...      1
10930  È un segnale di forza, certo, ma anche di una ...      1

[1000 rows x 2 columns]

In [13]:
df_val["label"].value_counts()

label
0    500
1    500
Name: count, dtype: int64

### Creazione del Test set dal Test set

In [14]:
df_test_completo = pd.read_csv("testset/desegma-it.subTaskA.with_labels.test.1117_1835.csv")

In [15]:
df_test_completo

                                                    text  label
0      L'idea di questi ragazzi è qualificarsi per gl...      0
1      Scarponi, interpellato dopo l'arrivo, non ha e...      1
2      "In altre parole, l'autore del saggio 'The Imp...      1
3      Un atto di coraggio disperato, un sacrificio c...      1
4      Bergoglio, che l'anno scorso andò nel carcere ...      0
...                                                  ...    ...
15130  Nelle foto scattate a Qusair, in Siria, gli AP...      0
15131  Hanno votato a favore Pd, Fratelli d'Italia, P...      0
15132  "Sono pronti - ha detto - e li metto a disposi...      0
15133  Anche l' africo di looking per la prevenzione ...      1
15134  La partenza di Bertagnolli era stata tenuta in...      1

[15135 rows x 2 columns]

In [16]:
df_test_completo["label"].value_counts()

label
1    7583
0    7552
Name: count, dtype: int64

In [17]:
test_class0 = df_test_completo[df_test_completo["label"] == 0].sample(n=500, random_state = 42)
test_class1 = df_test_completo[df_test_completo["label"] == 1].sample(n=500, random_state = 42)

In [18]:
df_test = pd.concat([test_class0, test_class1])
df_test["label"].value_counts()

label
0    500
1    500
Name: count, dtype: int64

In [20]:
df_train.to_csv("df_train.csv")
df_val.to_csv("df_val.csv")
df_test.to_csv("df_test.csv")